import { Injectable } from '@angular/core';
import { ProductType } from '../models/product';
import { Category } from '../models/category';

@Injectable({ providedIn: 'root' })
export class ProductMockService {
  getCategories(): Category[] {
    return [{
      id: 0,
      name: "Alkohol",
      displayName: "Alkohol",
      products: [{
        id: '0',
        createdOn: new Date('17.01.2022'),
        modifiedOn: new Date('17.01.2022'),
        name: 'Baumgartner Märzen',
        price: 5.1,
        shortDescription: 'Bier',
        sortOrder: 1,
        currency: '€',
        type: ProductType.DRINK,
        amount: 500,
        unit: 'ml',
      },
      {
        id: '1',
        createdOn: new Date('22.01.2022'),
        modifiedOn: new Date('25.01.2022'),
        name: 'Spritzer Weiß',
        price: 4.5,
        shortDescription: 'Wein',
        sortOrder: 2,
        currency: '€',
        type: ProductType.DRINK,
        amount: 500,
        unit: 'ml',
      }]
    }, {
      id: 1,
      name: "Limo",
      displayName: "Limo",
      products: [{
        id: '2',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Cola Zero',
        price: 5.1,
        shortDescription: 'Cola',
        sortOrder: 3,
        currency: '€',
        type: ProductType.DRINK,
        amount: 250,
        unit: 'ml',
      },
      {
        id: '3',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Almdudler Leitung',
        price: 3.80,
        shortDescription: 'Almdudler',
        sortOrder: 3,
        currency: '€',
        type: ProductType.DRINK,
        amount: 250,
        unit: 'ml',
      }],
    },
    {
      id: 2,
      name: "Essen",
      displayName: "Essen",
      products: [{
        id: '4',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Leberkäsesemmel',
        price: 2.50,
        shortDescription: 'Leberkäsesemmel',
        sortOrder: 4,
        currency: '€',
        type: ProductType.FOOD,
        amount: 250,
        unit: 'ml',
      }, {
        id: '5',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Käse-Leberkäsesemmel',
        price: 2.70,
        shortDescription: 'Käse-Leberkäsesemmel',
        sortOrder: 4,
        currency: '€',
        type: ProductType.FOOD,
        amount: 250,
        unit: 'ml',
      }, {
        id: '6',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Gummischlange',
        price: 1.00,
        shortDescription: 'Gummischlange',
        sortOrder: 4,
        currency: '€',
        type: ProductType.FOOD,
        amount: 250,
        unit: 'ml',
      }, {
        id: '7',
        createdOn: new Date('10.01.2022'),
        modifiedOn: new Date('30.01.2022'),
        name: 'Schlecker div.',
        price: 1.50,
        shortDescription: 'Schlecker',
        sortOrder: 4,
        currency: '€',
        type: ProductType.FOOD,
        amount: 250,
        unit: 'ml',
      }]
    }
    ]
  }
}
