image: node:16

stages:
  - lint
  - build
  - package


.distributed:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm i --cache .npm
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

variables:
  GIT_DEPTH: 0

lint:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci

# build:
#   stage: build
#   extends: .distributed
#   script:
#     - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
#   artifacts:
#     paths:
#       - dist/
#     expire_in: 2 hours
#   after_script:
#     - echo "'$CI_PROJECT_DIR'"
#     - cp $CI_PROJECT_DIR/Dockerfile dist/
#   cache:
#     paths:
#       - node_modules/

build:
  image: docker:stable
  stage: package
  before_script:
    - echo "inn-calculator:'$CI_CONCURRENT_ID'"
  script:
    - IMAGE_NAME="inn-calculator:$CI_CONCURRENT_ID"
    - docker build --pull -t "$IMAGE_NAME" -f Dockerfile .