image: node:12.16.3-alpine3.11

stages:
  - setup
  - distributed-tasks

install:deps:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
      - .yarn
    policy: pull-push
  stage: setup
  interruptible: true
  script:
    - yarn install --pure-lockfile --cache-folder .yarn
  artifacts:
    paths:
      - node_modules

.distributed:
  stage: distributed-tasks
  interruptible: true
  artifacts:
    paths:
      - node_modules/.cache/nx

format:
  extends: .distributed
  script:
    - CI_BASE_SHA=$([[ "$CI_COMMIT_REF_SLUG" == "master" ]] && echo "master~1" || echo "master")
    - yarn format:check --base=$CI_BASE_SHA

lint:
  extends: .distributed
  parallel: 8
  script:
    - node ./tools/scripts/run-many.js lint $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG

test:
  extends: .distributed
  parallel: 8
  script:
    - node ./tools/scripts/run-many.js test $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG --parallel

build:
  extends: .distributed
  parallel: 2
  script:
    - node ./tools/scripts/run-many.js build $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG --prod
  artifacts:
    paths:
      - node_modules/.cache/nx
      - dist