image: node:16

stages:
  - test
  - build

.distributed:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm i
    - yarn add @yarnpkg/parsers
    - yarn add @yarnpkg/lockfile
    - npm ci

variables:
  GIT_DEPTH: 0

format-check:
  stage: test
  extends: .distributed
  script:
    - npx nx format:check

lint:
  stage: test
  extends: .distributed
  script:
    - npx nx -t lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - npx nx -t test --parallel=3 --configuration=ci

build:
  stage: build
  extends: .distributed
  script:
    - npx nx -t build --parallel=3